# Generated by Django 3.2 on 2021-04-30 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('orderNo', models.CharField(max_length=200)),
                ('tracking_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('courier', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('destination_country_iso3', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=200)),
                ('articleNo', models.CharField(max_length=200)),
                ('articleImageUrl', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(verbose_name='date recorded')),
                ('status', models.CharField(max_length=200)),
                ('status_text', models.CharField(max_length=200)),
                ('status_details', models.CharField(max_length=200)),
                ('tracking_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.tracking')),
            ],
        ),
    ]
