# Generated by Django 3.2 on 2021-04-30 08:41

import pandas as pd

from django.db import migrations


def my_function(apps, schema_editor):
    # load checkpoints file
    checkpoints = pd.read_csv('challenge/data/checkpoints.csv', delimiter=';')
    trackings = pd.read_csv('challenge/data/trackings.csv', delimiter=';')

    # load tracking and checkpoint objects
    Tracking = apps.get_model("challenge", "Tracking")
    Checkpoint = apps.get_model("challenge", "Checkpoint")

    for i, row in trackings.iterrows():
        t = Tracking(
            orderNo=row['orderNo'],
            tracking_number=row['tracking_number'],
            courier=row['courier'],
            street=row['street'],
            zip_code=row['zip_code'],
            city=row['city'],
            destination_country_iso3=row['destination_country_iso3'],
            email=row['email'],
            articleNo=row['articleNo'],
            articleImageUrl=row['articleImageUrl'],
            quantity=row['quantity'],
            product_name=row['product_name'])
        t.save()

    for i, row in checkpoints.iterrows():
        tracking_number = row['tracking_number']
        # assume that tracking numbers are unique (a constraint in the model)
        # get the correct tracking object from the db
        t = Tracking.objects.filter(tracking_number=tracking_number)[0]
        c = Checkpoint(tracking_number=t,
                       location=row['location'],
                       timestamp=row['timestamp'],
                       status=row['status'],
                       status_text=row['status_text'],
                       status_details=row['status_details'])
        c.save()
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(my_function)
    ]
